# Site settings
title: "승욱'Resume"
description: "A resume template for tbvjqkdlcm1 and GitHub Pages sites."

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "true"
resume_name:                    "seungwook B.simpson"
resume_title:                   "About me"

# used for the contact button in _layouts/resume.html
resume_contact_email:           "tbvjqkdlcm1@naver.com"

# the next two items are used for schema itemprops in _layouts/resume.html
# resume_contact_telephone:       "555-7334"
# resume_contact_address:         "742 Evergreen Terrace, Springfield"

# resume_header_contact_info:     "742 Evergreen Terrace, Springfield • 555-7334 • lisasimpson@youremailaddress.com"
display_header_contact_info:    "false"

resume_header_intro: "<p>한때는 창업동아리 활동도 했었던 개발에 진심인 사람입니다. 전자/반도체 전공을 하였지만 매번 팀프로젝트 때마다 의식의 무언가에 이끌려 소프트웨어쪽을 도맡아 했었고 결국 늦게나마 과거에 하고싶었던 개발자에 다시 걸음마를 내딘 사람입니다.! </p>"

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work:        "yes"

# Decide which sections to use
# comment out to hide
resume_section_experience:      true
resume_section_education:       true
resume_section_projects:        true
resume_section_skills:          true
resume_section_recognition:     False
resume_section_links:           False
resume_section_associations:    False
# resume_section_interests:       true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url:            "https://github.com/tbvjqkdlcm1"
#   resume_twitter_url:           "http://twitter.com/jglovier"
#   resume_dribbble_url:          "https://dribbble.com/jag"
  resume_facebook_url:          "https://www.facebook.com/seungwook5191"
#   resume_linkedin_url:          "https://www.linkedin.com/in/joelglovier"
  # resume_instagram_url:         "insert your Instagram URL here"
  resume_notion_url:           "https://www.notion.so/Python-Study-Room-1fdb1b178fb048d8b2307508aa54d8fe"
#   resume_medium_url:            "https://medium.com/@jglovier
  resume_instagram_url:           "https://www.instargram.com/bsw6580"
resume_print_social_links:      true

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
